### ISSUE TITLE
Questions about exception propagation in Armeria gRPC client with a RetryingClient decorator

### ISSUE THREAD

**Issue by Lincong** [line/armeria#4558] opened 2022-12-01 20:15 UTC
Hi there! I have 2 questions about how exception propagation behavior in Armeria gRPC client with a RetryingClient decorator. It seems to me that there could be a bug.

## Setup
Armeria version: 1.16.0

### Client setup
I build a gRPC client stub with a [ClientBuilder](https://github.com/line/armeria/blob/c8d1f5ef142f65fd79bd01b87d8155d220c9d0b9/core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java) and I add 3 decorators to the `ClientBuilder` as shown below:

```scala
// Please note that "Site A/B/C/D" mentioned in the comment below will be referred in later discussion.

// Decorator 1
clientBuilder.decorator((delegate, ctx, req) => {
    val httpResponse = delegate.execute(ctx, req)
    httpResponse
        .mapHeaders(respHeaders => {
             // Site A
             // 1. create an exception based on the response header content.
             // 2. throw the created exception.
        }
})

// Decorator 2
clientBuilder.decorator((delegate, ctx, req) => {
    ctx.log() // ClientRequestContext
      .whenComplete()
      .thenAccept(requestLog => {
          val exception = requestLog.responseCause()
          // The above `exception` is always null except in the case where
          // the last retry attempt fails.
          // Site B
       })
    delegate.execute(ctx, req)
})

// Decorator 3
val retryDecorator = RetryingClient.newDecorator(createRetryConfig())
clientBuilder.decorator(retryDecorator)

def createRetryConfig(): RetryConfig = {
   // ...
   val retryRuleBuilder = RetryRule.builder()
   retryRuleBuilder.onException((_: ClientRequestContext, cause: Throwable) => {
     // This callback is NEVER invoked.
     // Site C
   })
   retryRuleBuilder.onResponseTrailers((ctx, trailers) => {
     // This callback is invoked. The retry decision is made based on `trailers`
     // Site D
   })
   // Create a RetryConfig with the above `retryRuleBuilder` and return it.
}
```

### Test setup
I wrote a test where a client with above decorators send one request to a server which always fails the requests and populates the response header with some error information. When the client receives the response, I expect the `decorator 1`'s `httpResponse.mapHeaders` callback (`Site A`) is invoked and an exception is created and thrown there. Then I expect the client to retry up to 3 times and eventually fail (because the server always fails the request and triggers an exception on the client side).

## Observations

1. Retry kicked in and 3 requests were sent sequentially. All 3 attempts failed that lead to client stub invocation failure. This behavior is expected :) 
2. The order of invocation during each request attempt: `Site A --> Site D --> Site B`. Note that `Site C` is never invoked.
3. In the first 2 request attempts at `Site B`,  `requestLog.responseCause() == null`. However, in the 3rd/final request attempt at `Site B`, `requestLog.responseCause() == exception_thrown_at_Site A`.

## Questions
1. For `observation 2`, why does `Site C` never invoked? Is it a bug or I did something wrong?
2. For `observation 3`, is this the expected/correct behavior? Specifically, does Armeria intentionally try to hide the exception from `Site B` (the ctx.log().whenComplete() callback) until the max retry attempt is reached? If it is intentional, could you share the rationale behind this design?

**Comment by Lincong** [comment] 2022-12-01 20:46
I read Armeria code [RetryingClient](https://github.com/line/armeria/blob/9e7c016e45be91d2b0a48c1ff258e100e9c655c5/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java) to better understand its behavior. Here are my findings (and more questions):

## For "question 1"
[retryRule.shouldRetry(derivedCtx, responseCause)](https://github.com/line/armeria/blob/9e7c016e45be91d2b0a48c1ff258e100e9c655c5/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java#L401) is called and the `responseCause` come from [here](https://github.com/line/armeria/blob/9e7c016e45be91d2b0a48c1ff258e100e9c655c5/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java#L355) (shown below)

```java
final Throwable responseCause = 
    log.isAvailable(RequestLogProperty.RESPONSE_CAUSE) ? log.responseCause() : null;
```
If `responseCause` is null, `Site C` is not invoked because `retryRule.shouldRetry` consider it as no exception. Interestingly, my debugger shows that in the above code `log.isAvailable(RequestLogProperty.RESPONSE_CAUSE) == true` BUT `log.responseCause() == null`. It confuses me. 
Is this a bug or my misunderstanding of `RequestLog`'s semantics?

My debugger also shows that exception thrown at `Site A` is set to `response0` ([here](https://github.com/line/armeria/blob/9e7c016e45be91d2b0a48c1ff258e100e9c655c5/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java#L332)) as shown below:

```java
final HttpResponse response0 = cause != null ? HttpResponse.ofFailure(cause) : null;
```
Then `response0` is passed to the `handleResponse` method. So the question is: why doesn't `handleResponse` pass `response0` to `retryRule.shouldRetry` (and instead it passes `responseCause`)?

## For "question 2"
I tried to understand how `RetryingClient` triggers the invocation of `Site B` (the ctx.log().whenComplete() callback). I realized that in [handleRetryDecision](https://github.com/line/armeria/blob/9e7c016e45be91d2b0a48c1ff258e100e9c655c5/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java#L439) method (shown below):

1. `abortResponse(originalRes, derivedCtx)` triggers the invocation of `Site B` after request attempt 1 and 2 fails. `derivedCtx.log().responseCause() == null`. This probably explains why the exception is **not** presented to `Site B`. But why is `derivedCtx.log().responseCause() == null`? Is this behavior expected/intentional?

2. `future.complete(originalRes)` triggers the invocation of `Site B` after the 3rd/final request attempt fails. `originalRes` contains the exception thrown at `Site A`. This probably explains why the exception **is** presented to `site B`.

```java
    private void handleRetryDecision(@Nullable RetryDecision decision, ClientRequestContext ctx,
                                     ClientRequestContext derivedCtx, HttpRequestDuplicator rootReqDuplicator,
                                     HttpRequest originalReq, HttpResponse returnedRes,
                                     CompletableFuture<HttpResponse> future, HttpResponse originalRes) {
        final Backoff backoff = decision != null ? decision.backoff() : null;
        if (backoff != null) {
            final long millisAfter = useRetryAfter ? getRetryAfterMillis(derivedCtx) : -1;
            final long nextDelay = getNextDelay(ctx, backoff, millisAfter);
            if (nextDelay >= 0) {
                abortResponse(originalRes, derivedCtx);
                scheduleNextRetry(
                        ctx, cause -> handleException(ctx, rootReqDuplicator, future, cause, false),
                        () -> doExecute0(ctx, rootReqDuplicator, originalReq, returnedRes, future),
                        nextDelay);
                return;
            }
        }
        onRetryingComplete(ctx);
        future.complete(originalRes);
        rootReqDuplicator.close();
    }
```

**Comment by Lincong** [comment] 2022-12-01 20:49
In my use case, `question 1` is more important than `question 2`. Because it will be a problem for us if the retry decorator cannot access exception thrown at "decorator 1" (Site A).

**Comment by minwoox** [comment] 2022-12-02 03:19
> log.isAvailable(RequestLogProperty.RESPONSE_CAUSE) == true BUT log.responseCause() == null. It confuses me.
Is this a bug or my misunderstanding of RequestLog's semantics?

It's not a bug. Sorry about confusing you.
It returns null if the response was successful.
https://github.com/line/armeria/blob/b1374d772c3c204a6fa26c082bf7722f4410a72e/core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java#L143

When `RequestLogBuilder.endResposne()` is called, it sets the availabilities of all properties including `RESPONSE_CAUSE`.
That's why we always check if `log.responseCause()` is `null` or not. 
https://github.com/line/armeria/blob/98cfcec6d695f49d9289c6d440c70ba971d3e18d/core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java#L321-L322
We are also returning `null` for `responseContent()` if the content wasn't set when the response is complete.
However, I agree that it's confusing. Let me talk to the team if we can improve it.

> why doesn't handleResponse pass response0 to retryRule.shouldRetry (and instead it passes responseCause)?

I think it's because we wanted to handle the cause it in one place. However, I think it's not a good idea and fix to handle the cause directly. Let me make a PR for that.

**Comment by minwoox** [comment] 2022-12-02 03:21
> This probably explains why the exception is not presented to Site B. But why is derivedCtx.log().responseCause() == null? Is this behavior expected/intentional?

Not intentional and we can fix it. 😄 

> This probably explains why the exception is presented to site B.

That's exactly. 👍

**Comment by Lincong** [comment] 2022-12-02 05:26
Thanks @minwoox for your clarification.

IIUC you will make 2 fixes/changes with which the behavior of my test setup will be:

1. When an exception is thrown at `Site A` will be passed to `Site C` so that I can make retry decisions based on the exception.

2. At the end of every failed retry attempt, `Site B` will always be able to access the exception thrown at `Site A` by `requestLog.responseCause()`. For example, if the max retry attempt is 3 and every retry attempt fails (`Site A` throws an exception), `Site B` will be able to access the exception 3 times sequentially.

Could you confirm my above understanding is correct? Thanks!

**Comment by minwoox** [comment] 2022-12-02 05:35
> Could you confirm my above understanding is correct? 

That is correct. 😄

**Comment by Lincong** [comment] 2022-12-02 05:44
> > Could you confirm my above understanding is correct?
> 
> That is correct. 😄

This is great! Should we leave this issue open until you merge those 2 fixes/changes and make a new release?

**Comment by minwoox** [comment] 2022-12-02 06:56
> Should we leave this issue open until you merge those 2 fixes/changes and make a new release?

We can close this when #4559 is merged. The next release will be in mid-December. Thanks!

**Comment by Lincong** [comment] 2022-12-02 18:08
> > Should we leave this issue open until you merge those 2 fixes/changes and make a new release?
> 
> We can close this when #4559 is merged. The next release will be in mid-December. Thanks!

Thanks @minwoox for the quick fix! I left some comments there.
Is this fix mostly likely going to be part of the `1.21.0` release?

**Comment by minwoox** [comment] 2022-12-06 05:33
Sorry about that I missed this comment. 😓 

> Is this fix mostly likely going to be part of the 1.21.0 release?

I think so.

> Is it there a chance that this fix can be back ported to 1.16.0?

If you want, I can release a patch version. 😄

**Comment by Lincong** [comment] 2022-12-06 05:43
> If you want, I can release a patch version.

That'd be great! Here is the reason why it would be super helpful for us:

We are on `1.16.0` and my team currently does not have the resource/bandwidth to upgrade to the newest release version of Armeria. So, a patch fixing the issue in `1.16.0` would be the best.

Thanks! @minwoox

**Closed** 2022-12-06 13:23 UTC
Labels: defect

**Comment by minwoox** [comment] 2022-12-06 15:34
1.16.1 has been released. 😉 
https://repo.maven.apache.org/maven2/com/linecorp/armeria/armeria-bom/1.16.1/
https://github.com/line/armeria/commits/1cca43dec3b7cb84dc4131e228603dcf3b9caa7c
