### ISSUE TITLE
Provide well defined Grafana dashboard template

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3341] opened 2021-02-10 06:51 UTC
Related https://grafana.com/grafana/dashboards/4701
If we provide a well-defined default Grafana dashboard template,
our users do not have to spend much time figuring out which metric they need.

**Comment by anuraaga** [comment] 2021-02-10 08:12
Is it a duplicate of #2973? This has been requested for a long time :)

**Comment by minwoox** [comment] 2021-02-10 08:14
Ah, I missed that. Yes, it's duplicated. 😅

**Closed** 2021-02-10 08:14 UTC
Labels: new feature
