### ISSUE TITLE
DefaultUnhandledExceptionsReporter reports cleanup related issues

### ISSUE THREAD

**Issue by mauhiz** [line/armeria#4861] opened 2023-05-05 14:23 UTC
Observed this WARN:

```
Observed 8 unhandled exceptions in last 10000ms(10000000000ns). Please consider adding the LoggingService decorator to get detailed error logs. One of the thrown exceptions:

com.linecorp.armeria.common.ClosedSessionException: null
	at com.linecorp.armeria.common.ClosedSessionException.get(ClosedSessionException.java:35)
	at com.linecorp.armeria.server.HttpServerHandler.cleanup(HttpServerHandler.java:243)
	at com.linecorp.armeria.server.HttpServerHandler.channelInactive(HttpServerHandler.java:236)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:430)
	at com.linecorp.armeria.server.Http2ServerConnectionHandler.channelInactive(Http2ServerConnectionHandler.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:206)
```

Well, we do have a LoggingService configured! But since this error doesn't happen on a specific request, `shouldReportUnhandledExceptions` is not set to false

As for the root cause, I found this other log

```
 Sending GOAWAY failed: lastStreamId '2147483647', errorCode '0', debugData ''. Forcing shutdown of the connection.
io.netty.handler.codec.http2.Http2ConnectionHandler#processGoAwayWriteResult
io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Broken pipe
```

So the client was not shutdown cleanly, causing an ignorable error to happen on cleaning up the inactive channel 

I think that the DefaultUnhandledExceptionsReporter should not WARN in such a case.

**Comment by jrhee17** [comment] 2023-05-08 01:28
> I think that the DefaultUnhandledExceptionsReporter should not WARN in such a case.

Agreed! Thanks for letting us know about this issue 😅    We'll try to get this fixed in the next release

**Comment by seonwoo960000** [comment] 2023-05-19 13:27
@jrhee17 May I look on the issue ? 😄

**Comment by jrhee17** [comment] 2023-05-20 07:24
> would it be possible for me to take a look at the issue?

Sure, go for it.

**Comment by jrhee17** [comment] 2023-05-20 07:28
> If it's alright, @mauhiz, could you please provide me with information on how to reproduce the problem?

The problem is reproducible by closing a request that isn't closed.
You can probably simulate closing the http connection with something like the following:

```
try (ClientFactory cf = ClientFactory.builder().build()) {
  final HttpResponse res = server.webClient(cb -> cb.factory(cf)).get("/streaming");
  await().until(() -> !server.requestContextCaptor().isEmpty());
}
```

**Comment by seonwoo960000** [comment] 2023-06-04 13:49
Hi @jrhee17, sorry for the late reply as I needed some time to understand the problem 😢. I've added a [test code](https://github.com/line/armeria/pull/4922) to reproduce the problem. 

Yet, upon executing the test code to replicate the issue, the `LoggingDecorator` intercepts the exceptions instead of `DefaultUnhandledexceptionReporter` reporting them. I think I'm missing something ...

**Comment by jrhee17** [comment] 2023-06-05 01:55
I think the scenario is possible if the `LoggingService` is not reached.

For instance, the decorator sequence does not necessarily need to be syncrhonous.

```
Server -> AuthService -> LoggingService -> HttpService
```

If `AuthService` only is reached, then I guess the log would be printed even if `LoggingService` is in the path.

**Comment by seonwoo960000** [comment] 2023-06-06 11:33
@jrhee17 Thank you for the explanation. I was able to reproduce above problem by using the examples you provided(by adding decorators which throws exceptions on certain conditions). 
```
Server -> CustomService(throws exception) -> LoggingService -> HttpService 
```
I found that when `CustomService` throws exception, even though LoggingService is configured, `DefaultUnhandledExceptionsReporter` would report the exceptions thrown by the `CustomService`. 

I was able to make `LoggingService` handle exceptions thrown by `CustomService` by moving the positions like below:
```
Server -> LoggingService -> CustomService(throws exception) -> HttpService
```

Rethinking about this issue, I wonder the behavior of `DefaultUnhandledExceptionsReporter` reporting unhandled exceptions(even though `LoggingService` is configured) is a weird behavior. Rather, can this behavior considered as a feature(reporting all the unhandled exceptions thrown while handling requests)? If it can, then how about fixing the log message? 

<b>as-is</b> 
```
Please consider adding the LoggingService decorator to get detailed error logs
```

<b>to-be</b> example 
```
Please consider adding the LoggingService decorator as the outermost decorator to get detailed error logs 
```

If this behavior is intolerable, I think we can fix it by adding a flag(such as `loggingServiceExists`) on the `ServerBuilder` and use it to turn `DefaultUnhandledExceptionsReporter`'s reporting feature on or off.

**Comment by jrhee17** [comment] 2023-06-07 02:56
Sure, how about the following message:
```
            logger.warn("Observed {} exceptions that didn't reach a LoggingService in the last {}. " +
                        "Please consider either adding a LoggingService or moving the " +
                        "LoggingService to an earlier timing.",
```

Also, I think that users can't do much about this kind of exception.
What do you think of also ignoring exceptions by checking `Exceptions.isExpected`?

```
    private static boolean isIgnorableException(Throwable cause) {
        if (Exceptions.isExpected(cause)) {
            return true;
        }
...
```

**Comment by seonwoo960000** [comment] 2023-06-07 07:34
Thank you for step by step guide. I opened a [PR]( Add exceptionShouldNotBeLoggedWhenClientDisconnectsAbruptly) and now we can talk about this issue there! 🚀

**Closed** 2023-06-14 10:41 UTC
Labels: defect
