### ISSUE TITLE
Test failure: `LazyDynamicEndpointGroupTest.emptyEndpoint()`

### ISSUE THREAD

**Issue by hexoul** [line/armeria#3576] opened 2021-05-18 08:21 UTC
https://github.com/line/armeria/pull/3505/checks?check_run_id=2608236536#step:7:2368
```
LazyDynamicEndpointGroupTest > emptyEndpoint() FAILED
    java.lang.AssertionError: 
    Expecting a throwable with cause being an instance of:
     <com.linecorp.armeria.client.UnprocessedRequestException>
    but was an instance of:
     <com.linecorp.armeria.common.stream.ClosedStreamException>
        at com.linecorp.armeria.client.grpc.LazyDynamicEndpointGroupTest.emptyEndpoint(LazyDynamicEndpointGroupTest.java:91)
16:59:33.055 [Thread-3] DEBUG c.l.armeria.client.ClientFactory - Closing the default client factories
16:59:33.070 [Thread-3] DEBUG c.l.armeria.client.ClientFactory - Closed the default client factories
```

**Comment by ikhoon** [comment] 2021-06-15 12:00
Duplicate of #3381

**Closed by ikhoon** 2021-06-15 12:00 UTC
