### ISSUE TITLE
Armeria doesn't stop between test suites when running with Spring Boot

### ISSUE THREAD

**Issue by jmadureira** [line/armeria#4399] opened 2022-08-18 20:47 UTC
Consider the following scenario:

- A Spring Boot application backed by Armeria just like the one in the [examples](/line/armeria/tree/master/examples/spring-boot-minimal);
- We want to test our application using different configurations (for instance an application that uses different datasources, or caches, or something else)

One way to do this is to use Spring `@ContextConfiguration` where we inject the configurations we want to use. So if we reuse the [spring-boot-minimal](/line/armeria/tree/master/examples/spring-boot-minimal) example we would do something like the following:

```java
package example.springframework.boot.minimal;

// our import declarations

@ActiveProfiles("testbed")
@SpringBootTest(webEnvironment = WebEnvironment.NONE)
@ContextConfiguration(initializers = { HelloApplicationIntegrationTest.Initializer.class })
class HelloApplicationIntegrationTest {

    static class Initializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {
        public void initialize(ConfigurableApplicationContext configurableApplicationContext) {
            TestPropertyValues
                    .of("the property overrides we want to test against")
                    .applyTo(configurableApplicationContext.getEnvironment());
        }
    }

// our test cases and so on

}
```

If we debug this test suite with a breakpoint at the [ArmeriaServerGracefulShutdownLifecycle.java](https://github.com/line/armeria/blob/be4250fc937233af130dfe8ed93b740718176c7d/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaServerGracefulShutdownLifecycle.java#L70) the execution will stop at the `stop()` method during shutdown as expected.

The issue here is that if we create another test class to test another configuration setup:

```java
package example.springframework.boot.minimal;

// our import declarations

@ActiveProfiles("testbed")
@SpringBootTest(webEnvironment = WebEnvironment.NONE)
@ContextConfiguration(initializers = { HelloApplicationIntegrationTest2.Initializer.class })
class HelloApplicationIntegrationTest2 {

    static class Initializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {
        public void initialize(ConfigurableApplicationContext configurableApplicationContext) {
            TestPropertyValues
                    .of("the property overrides we want to test against different than the ones used at HelloApplicationIntegrationTest")
                    .applyTo(configurableApplicationContext.getEnvironment());
        }
    }

// same tests as HelloApplicationIntegrationTest

}
```

... and debug the tests again the `stop()` method at [ArmeriaServerGracefulShutdownLifecycle.java](https://github.com/line/armeria/blob/be4250fc937233af130dfe8ed93b740718176c7d/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaServerGracefulShutdownLifecycle.java#L70) will be called twice (as expected since we wanted to test 2 different `Server` instances) but **at the end of the entire test execution** and not at the end of each test suite.

This means that given a sufficiently big project that needs to test different configurations (like the one I'm currently working on) we will eventually reach an out of memory error because all `Server` instances are only stopped at the end of the execution.

Currently what we are seeing in our tests is the following:

```
// several log entries stating that an Armeria Server instance is shutting down
Error:  Surefire is going to kill self fork JVM. The exit has elapsed 30 seconds after System.exit(0).
```

My guess is that Spring's Application Context is bound to the lifecycle of the JVM (shutdown hook or something similar) and Armeria is bound to Spring's Application Context lifecycle which explains why it is stopping when Spring stops as well.

Is this the intended behaviour? Shouldn't Spring stop the current Armeria Server before launching the new one or am I missing a piece of configuration?

**Comment by minwoox** [comment] 2022-08-19 02:11
Thanks for the report, @jmadureira!
@kojilin Would you mind taking a look at this? 😄

**Comment by heowc** [comment] 2022-08-30 01:16
I've analyzed this briefly. However, I haven't been able to find a solution, but I'd like to share an interesting fact.

This is first executed by SpringApplicationShutdownHook .
And in the process of destroying the beans, the SmartLiftcycle beans go through a separate operation process by the LifecycleProcessor. At this point you can see that the server is trying to get down.

What's interesting here is that not only Armeria but also applications like Tomcat work the same.

So here's what we're looking for to solve the problem:
- We need to be able to know when to destroy (or recycle) beans for an existing context when the context changes in Spring.
- If not, we need to check if the same bean is available.

**Comment by minwoox** [comment] 2022-09-12 13:56
@heowc Thanks for taking a look at it. 😄  I found out that we need to add `@DirtiesContext`. 😅 

@jmadureira Let's add `@DirtiesContext` to the class because this changes the context.
```
 * <p>Use this annotation if a test has modified the context &mdash; for
 * example, by modifying the state of a singleton bean, modifying the state
 * of an embedded database, etc. Subsequent tests that request the same
 * context will be supplied a new context.
```
https://github.com/spring-projects/spring-framework/blob/main/spring-test/src/main/java/org/springframework/test/annotation/DirtiesContext.java#L32-L35

**Comment by jmadureira** [comment] 2022-09-12 16:30
@heowc and @minwoox thank you for the info. I'll test this out and let you know.

**Comment by jmadureira** [comment] 2022-09-13 09:00
@minwoox the `@DirtiesContext` works on my project as well and it ought to be the correct approach.

My 2 cents is that this should be included in the spring-boot examples otherwise someone will eventually bump into this problem.

Feel free to close this issue whenever you like.

Thank you and @heowc for your help.

**Comment by minwoox** [comment] 2022-09-13 09:03
> My 2 cents is that this should be included in the spring-boot examples otherwise someone will eventually bump into this problem.

That's a good suggestion. Are you interested in fixing the example?

**Comment by minwoox** [comment] 2024-05-24 09:19
Let me close this issue because it was not a bug.

**Closed by minwoox** 2024-05-24 09:19 UTC
Labels: defect
