### ISSUE TITLE
Response closed without grpc-status (Headers only)

### ISSUE THREAD

**Issue by AhmadVatani** [line/armeria#1586] opened 2019-02-12 11:12 UTC
Hi,
For send error to client, I'm using below code:
`responseObserver.onError(Status.INVALID_ARGUMENT.withDescription("Error description").asRuntimeException())`

In grpc web I got that error with below statusMessage and status 2:
`Response closed without grpc-status (Headers only)`

What should i do for get pretty format of error in grpc web?

**Comment by trustin** [comment] 2019-02-12 12:23
That looks like an unexpected behavior to me. Do you have a simple code that reproduces the problem, because we didn't see such an error before. /cc @anuraaga

**Comment by AhmadVatani** [comment] 2019-02-12 12:43
We are using [grpc-web](https://github.com/improbable-eng/grpc-web) implementation for TypeScript in front-end.

Here is grpc calling in TypeScript:
`grpc.unary(ProfileSecureService.ReadProfile, {
        host: ... ,
        request: ... ,
        metadata: ...,
        onEnd: res => {
          console.log(res);
        }
      }); `

And When get exception, in console log:

![screen shot 2019-02-12 at 16 07 45](https://user-images.githubusercontent.com/13574768/52636017-aeb28d80-2ee0-11e9-9128-8ba70b79f2db.png)

**Comment by anuraaga** [comment] 2019-02-12 12:53
Thanks will take a look. Also for reference, what version of the typescript gRPC-Web are you using?

**Comment by AhmadVatani** [comment] 2019-02-12 13:24
@anuraaga 
[grpc-web version 0.7.0](https://github.com/improbable-eng/grpc-web/releases/tag/0.7.0)
And Armeria version 0.79.0

**Comment by iEAmi** [comment] 2019-02-12 15:25
@anuraaga 
Armeria send grpc status in HTTP trailers but some browsers not support HTTP/2.0 trailers. I think this make problem.
I don't know netty-grpc how send grpc status!!!!!

**Comment by anuraaga** [comment] 2019-02-13 06:06
@AhmadVatani I have added a test case for grpc-web with an error in #1588. Can you compare it's business logic to yours, specifically https://github.com/line/armeria/blob/master/grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java#L159 ?

The server seems to be returning a correct response so I'm not sure why you're seeing the strange behavior on the browser. If you don't see anything obvious, it would be really great if you could set up a small repro with a HTML/JS and Java that could show the error - it'll take me some time to try to get those components set up to try myself, and I worry I won't be able to reproduce the error ><.

@iEAmi We don't use HTTP trailers when the content type is set to application/grpc-web - you can look at the test cases in `GrpcServiceServerTest` to see the behavior, where if it's a top-level error, the error is returned in normal headers, while for successful responses or mid-stream errors, it is returned as a serialized payload at the end of the response.

**Comment by iEAmi** [comment] 2019-02-14 13:49
@anuraaga  You right 🙏🏻

**Comment by trustin** [comment] 2019-02-15 08:21
Closing as 'not a bug', then. Please feel free to reopen if it's really a bug.

**Comment by AhmadVatani** [comment] 2019-02-23 06:35
@trustin @anuraaga 
I'm sorry for the delay.
Finally after some debugging request and response data and compare armeria response with gRPC, I found the problem. It's related to CORS headers!
`Grpc-Message` and `Grpc-Status` headers are neaded to be exposed for grpc-web requests!
You can add them by default in armeria.

**Comment by anuraaga** [comment] 2019-02-24 06:01
Ah this makes sense - I haven't used gRPC-web with CORS ever before. Actually I'm not so familiar with the CORS implementation in Armeria, @hyangtack do you think you would be able to help with this? Right now `GrpcService` only responds to normal requests but I think it needs to be tweaked to respond to origin requests too.

**Comment by hyangtack** [comment] 2019-02-25 00:23
@AhmadVatani Thank you for reporting! @anuraaga Ok, I will take a look on this today. :-)

**Comment by hyangtack** [comment] 2019-02-25 02:11
@AhmadVatani I guess you can get `Grpc-Message` and `Grpc-Status` headers from the response if you decorate your gRPC service with `CorsService` decorator. The following code is very simple example which adds `access-control-expose-headers: grpc-status, grpc-message` header to the every response if the request contains `origin` header.

```
sb.serviceUnder("/", new GrpcServiceBuilder().addService(...)
        .build()
        .decorate(CorsServiceBuilder.forAnyOrigin()
        							.exposeHeaders(GrpcHeaderNames.GRPC_STATUS, GrpcHeaderNames.GRPC_MESSAGE)
        							.newDecorator()));
```

If you didn't configure CORS for your gRPC service, you need to do it first with the following document.
- https://line.github.io/armeria/server-grpc.html#id1

You can also refer to the following document for configuring CORS. 
- https://line.github.io/armeria/server-cors.html

Please let me know how it goes! :-)

**Comment by AhmadVatani** [comment] 2019-02-25 10:38
@hyangtack Yes, of course! we did it and now working fine. Thanks

**Closed** 2019-02-25 10:39 UTC

**Comment by anuraaga** [comment] 2019-02-25 14:06
Thanks for confirming! @hyangtack do we need to update the documentation to mention `exposeHeaders`? Looks like we only have the accepted headers documented currently.

**Comment by hyangtack** [comment] 2019-02-26 01:03
@anuraaga I will update the document today. :-)
