### ISSUE TITLE
Allow `Http{Status,Response}Exception` to have `RequestLog.responseCause()`.

### ISSUE THREAD

**Issue by trustin** [line/armeria#2656] opened 2020-04-06 08:24 UTC
Armeria currently handles `Http{Status,Response}Exception` specially. When it is thrown by a user, the response generated from the exception is sent as it is and `RequestLog` is ended successfully.

However, in some case, a user wants to send a custom response using `Http{Status,Response}Exception` while ending the `RequestLog` exceptionally.

It would be nice if a user can specify a cause when creating `Http{Status,Response}Exception` and then `HttpServerHandler` uses the given cause when ending the `RequestLog`, i.e. `ctx.logBuilder().endResponse(httpResponseException.getCause())`

**Comment by Charliocat** [comment] 2020-04-24 14:34
Hello, I'd like to try solving this. I've been looking at the code and I came up with some questions:
- Should I specify a setter for the cause when creating the `Http{Status,Response}Exception`, or should I by another way?
- In the `HttpServerHandler` is the cause already handled? If its not could you tell me where I should add the new behaviour?

**Comment by ikhoon** [comment] 2021-11-16 01:59
The problem has been fixed by #3674

**Closed by ikhoon** 2021-11-16 01:59 UTC
Labels: new feature
