### ISSUE TITLE
Shaded Armeria jar contains redundant dependencies

### ISSUE THREAD

**Issue by sh1n1chi8acker** [line/armeria#1001] opened 2018-02-09 06:42 UTC
Hi, I'm using shaded jar, but it contains redundant dependencies.

https://line.github.io/armeria/setup-maven.html
```
Armeria also provides its artifacts as a shaded JAR so that it can coexist with other components better. The following is the list of the shaded dependencies:

Caffeine
completable-futures
fastutil
Guava
JCTools
Reflections
```

But armeria-shaded:jar:0.58.0 contains

```
[INFO] +- com.linecorp.armeria:armeria-shaded:jar:0.58.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.4:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.4:compile
[INFO] |  +- com.github.ben-manes.caffeine:caffeine:jar:2.6.1:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- com.google.guava:guava:jar:24.0-jre:compile
[INFO] |  |  \- org.checkerframework:checker-compat-qual:jar:2.3.2:compile
[INFO] |  +- com.spotify:completable-futures:jar:0.3.2:compile
[INFO] |  +- io.micrometer:micrometer-core:jar:1.0.0-rc.9:compile
[INFO] |  |  +- org.hdrhistogram:HdrHistogram:jar:2.1.10:compile
[INFO] |  |  \- org.latencyutils:LatencyUtils:jar:2.0.3:compile
[INFO] |  +- io.netty:netty-codec-http2:jar:4.1.21.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.21.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.21.Final:compile
[INFO] |  |  \- io.netty:netty-handler:jar:4.1.21.Final:compile
[INFO] |  +- io.netty:netty-resolver-dns:jar:4.1.21.Final:compile
[INFO] |  |  +- io.netty:netty-resolver:jar:4.1.21.Final:compile
[INFO] |  |  \- io.netty:netty-codec-dns:jar:4.1.21.Final:compile
[INFO] |  +- io.netty:netty-tcnative-boringssl-static:jar:2.0.7.Final:compile
[INFO] |  +- io.netty:netty-transport:jar:4.1.21.Final:compile
[INFO] |  |  \- io.netty:netty-buffer:jar:4.1.21.Final:compile
[INFO] |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.21.Final:compile
[INFO] |  |  +- io.netty:netty-common:jar:4.1.21.Final:compile
[INFO] |  |  \- io.netty:netty-transport-native-unix-common:jar:4.1.21.Final:compile
[INFO] |  +- io.netty:netty-transport-native-unix-common:jar:linux-x86_64:4.1.21.Final:compile
[INFO] |  +- it.unimi.dsi:fastutil:jar:8.1.1:compile
[INFO] |  +- org.javassist:javassist:jar:3.22.0-GA:compile
[INFO] |  +- org.jctools:jctools-core:jar:2.1.1:compile
[INFO] |  \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
```

As of armeria-shaded:jar:0.55, not contains
```
[INFO] +- com.linecorp.armeria:armeria-shaded:jar:0.55.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.2:compile
[INFO] |  +- io.micrometer:micrometer-core:jar:1.0.0-rc.5:compile
[INFO] |  |  +- org.hdrhistogram:HdrHistogram:jar:2.1.10:compile
[INFO] |  |  \- org.latencyutils:LatencyUtils:jar:2.0.3:compile
[INFO] |  +- io.micrometer:micrometer-registry-prometheus:jar:1.0.0-rc.5:compile
[INFO] |  +- io.netty:netty-transport:jar:4.1.17.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.17.Final:compile
[INFO] |  |  \- io.netty:netty-resolver:jar:4.1.17.Final:compile
[INFO] |  +- io.netty:netty-codec-http2:jar:4.1.17.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.17.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.17.Final:compile
[INFO] |  |  \- io.netty:netty-handler:jar:4.1.17.Final:compile
[INFO] |  +- io.netty:netty-resolver-dns:jar:4.1.17.Final:compile
[INFO] |  |  \- io.netty:netty-codec-dns:jar:4.1.17.Final:compile
[INFO] |  +- io.netty:netty-transport-native-unix-common:jar:linux-x86_64:4.1.17.Final:compile
[INFO] |  |  \- io.netty:netty-common:jar:4.1.17.Final:compile
[INFO] |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.17.Final:compile
[INFO] |  |  \- io.netty:netty-transport-native-unix-common:jar:4.1.17.Final:compile
[INFO] |  +- io.netty:netty-tcnative-boringssl-static:jar:2.0.7.Final:compile
[INFO] |  +- io.prometheus:simpleclient_common:jar:0.1.0:compile
[INFO] |  |  \- io.prometheus:simpleclient:jar:0.1.0:compile
[INFO] |  +- org.reactivestreams:reactive-streams:jar:1.0.1:compile
[INFO] |  \- org.javassist:javassist:jar:3.22.0-GA:compile
```

**Comment by trustin** [comment] 2018-02-09 07:01
Oops! This looks loke a regression in the recent refactoring of our build script. Will take a look.

**Comment by trustin** [comment] 2018-02-09 07:52
Fix coming soon. Will release 0.58.1 once merged.
https://github.com/line/gradle-scripts/pull/7

**Comment by trustin** [comment] 2018-02-09 08:02
Fixed

**Closed by trustin** 2018-02-09 08:02 UTC
Labels: defect

**Comment by trustin** [comment] 2018-02-09 08:06
Release in progress: https://github.com/line/armeria/releases/tag/armeria-0.58.1

**Comment by trustin** [comment] 2018-02-09 08:06
.. and thanks a lot for reporting this issue quickly!

**Comment by trustin** [comment] 2018-02-09 09:09
@sh1n1chi8acker Could you let us know if the problem is gone in 0.58.1?

**Comment by sh1n1chi8acker** [comment] 2018-02-09 09:15
@trustin 
Thanks.
I have confirmed 0.58.1 is OK.
💯
