### ISSUE TITLE
An incorrect `ServiceRequestContext.localAddress()` is returned for domain sockets with abstract namespace

### ISSUE THREAD

**Issue by jrhee17** [line/armeria#5080] opened 2023-07-28 01:16 UTC
We've received a report regarding usage of abstract namespace unix domain sockets.

Specifically, it seems like `ServiceRequestContext.localAddress()` returns an `InetSocketAddress` with hostAddress ([0.0.0.0], port: 1) instead of a `DomainSocketAddress`.

We may want to make sure that the correct `DomainSocketAddress` is returned for both `local|remote` addresses.
Note that testing with non-abstract namespaces in a Mac env. seems to be working correctly.

ref: https://discord.com/channels/1087271586832318494/1125302155725787177/1133985691576049715

**Comment by jrhee17** [comment] 2023-07-28 01:17
cc. @chris-ryan-square

**Comment by chris-ryan-square** [comment] 2023-07-31 01:34
I did another test and can confirm that I am not getting a `DomainSocketAddress`.

I am unsure if it is relevant, but the server I am using is listening on port 8080 as well as the abstract namespace socket.  Given the nature of the deployment and the access path, the request causing the problem is definitely going via the domain socket.

**Comment by chris-ryan-square** [comment] 2023-07-31 04:45
And I can confirm that the non abstract namespace works as expected.

**Comment by chris-ryan-square** [comment] 2023-08-02 00:36
Use this code on a Linux box to replicate:

```kotlin
import com.linecorp.armeria.common.HttpResponse
import com.linecorp.armeria.common.util.DomainSocketAddress
import com.linecorp.armeria.server.Server

fun main(args: Array<String>) {
    val server = Server.builder()
        .http(DomainSocketAddress.of("\u0000testsocket"))
        .service("/") { ctx, req ->
            val clazzName = ctx.localAddress().javaClass.simpleName
            HttpResponse.of(clazzName)
        }
        .build()

    server.start().join()
}
```

Create the socket:

```bash
socat tcp-listen:12345 abstract-listen:@testsocket
```

Then use curl:

```bash
curl --abstract-unix-socket testsocket "http://localhost/"
```

It will currently return `InetSocketAddress` instead of `DomainSocketAddress`

**Comment by chris-ryan-square** [comment] 2023-08-21 02:52
I see there's a fix merged - will this be out in the next release?

**Comment by ikhoon** [comment] 2023-08-21 03:04
Yes, the new version is expected to be released this week.

**Closed by ikhoon** 2023-08-21 03:04 UTC
Labels: defect
