### ISSUE TITLE
'subscribed by other subscriber already' in FixedStreamMessage

### ISSUE THREAD

**Issue by Boozilla** [line/armeria#4392] opened 2022-08-14 12:35 UTC
Hello
Run a gRPC server application in `Armeria 1.17.1` and
During the stress test with 320 threads, the following stacktrace was obtained.
`useBlockingTaskExecutor` value is `true`
Why is this happening?

```
io.grpc.StatusException: UNKNOWN
	at io.grpc.Status.asException(Status.java:543) ~[grpc-api-1.47.0.jar:1.47.0]
	at com.linecorp.armeria.internal.common.grpc.GrpcLogUtil.rpcResponse(GrpcLogUtil.java:61) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.doClose(UnaryServerCall.java:206) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.AbstractServerCall.doClose(AbstractServerCall.java:254) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.AbstractServerCall.close(AbstractServerCall.java:219) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.AbstractServerCall.close(AbstractServerCall.java:209) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.AbstractServerCall.onError(AbstractServerCall.java:419) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.lambda$startDeframing$0(UnaryServerCall.java:120) ~[armeria-grpc-1.17.1.jar:na]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340) ~[na:na]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.startDeframing(UnaryServerCall.java:118) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.request(UnaryServerCall.java:109) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:555) ~[armeria-1.17.1.jar:na]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.IllegalStateException: subscribed by other subscriber already
	at com.linecorp.armeria.internal.common.stream.FixedStreamMessage.collect(FixedStreamMessage.java:189) ~[armeria-1.17.1.jar:na]
	... 11 common frames omitted
```

```
io.grpc.StatusException: UNKNOWN
	at io.grpc.Status.asException(Status.java:543) ~[grpc-api-1.47.0.jar:1.47.0]
	at com.linecorp.armeria.internal.common.grpc.GrpcLogUtil.rpcResponse(GrpcLogUtil.java:61) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.doClose(UnaryServerCall.java:206) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.AbstractServerCall.doClose(AbstractServerCall.java:254) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.AbstractServerCall.close(AbstractServerCall.java:219) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.AbstractServerCall.close(AbstractServerCall.java:209) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.AbstractServerCall.onError(AbstractServerCall.java:419) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.lambda$startDeframing$0(UnaryServerCall.java:129) ~[armeria-grpc-1.17.1.jar:na]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[na:na]
	at com.linecorp.armeria.internal.common.stream.FixedStreamMessage.collect(FixedStreamMessage.java:199) ~[armeria-1.17.1.jar:na]
	at com.linecorp.armeria.internal.common.stream.FixedStreamMessage.lambda$collect$2(FixedStreamMessage.java:186) ~[armeria-1.17.1.jar:na]
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:555) ~[armeria-1.17.1.jar:na]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454) ~[netty-buffer-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.buffer.AbstractByteBuf.duplicate(AbstractByteBuf.java:1199) ~[netty-buffer-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.buffer.AbstractUnpooledSlicedByteBuf.duplicate(AbstractUnpooledSlicedByteBuf.java:218) ~[netty-buffer-4.1.78.Final.jar:4.1.78.Final]
	at com.linecorp.armeria.common.ByteBufHttpData.byteBuf(ByteBufHttpData.java:197) ~[armeria-1.17.1.jar:na]
	at com.linecorp.armeria.common.HttpData.byteBuf(HttpData.java:434) ~[armeria-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.UnaryMessageDeframer.deframe(UnaryMessageDeframer.java:50) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.deframe(UnaryServerCall.java:139) ~[armeria-grpc-1.17.1.jar:na]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.lambda$startDeframing$0(UnaryServerCall.java:125) ~[armeria-grpc-1.17.1.jar:na]
	... 15 common frames omitted
```

**Comment by Boozilla** [comment] 2022-08-14 12:40
The client side stacktrace that generates the stress test traffic is below

```
21:35:32.509 [armeria-common-worker-nio-2-2] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: io.grpc.StatusRuntimeException: UNKNOWN
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:535)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create
	com.salesforce.reactorgrpc.stub.ClientCalls.oneToOne(ClientCalls.java:38)
Error has been observed at the following site(s):
	*_____Mono.create ⇢ at com.salesforce.reactorgrpc.stub.ClientCalls.oneToOne(ClientCalls.java:38)
	|_ Mono.transform ⇢ at com.salesforce.reactorgrpc.stub.ClientCalls.oneToOne(ClientCalls.java:57)
Original Stack Trace:
		at io.grpc.Status.asRuntimeException(Status.java:535)
		at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
		at com.linecorp.armeria.internal.client.grpc.ArmeriaClientCall.close(ArmeriaClientCall.java:499)
		at com.linecorp.armeria.internal.client.grpc.ArmeriaClientCall.transportReportStatus(ArmeriaClientCall.java:443)
		at com.linecorp.armeria.internal.common.grpc.GrpcStatus.reportStatus(GrpcStatus.java:338)
		at com.linecorp.armeria.internal.common.grpc.GrpcStatus.lambda$reportStatusLater$0(GrpcStatus.java:316)
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
		at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:259)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:300)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:292)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:429)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:372)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:328)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:314)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:436)
		at com.linecorp.armeria.internal.common.stream.DecodedStreamMessage$DecodingSubscriber.onComplete(DecodedStreamMessage.java:288)
		at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onComplete(DeferredStreamMessage.java:403)
		at com.linecorp.armeria.internal.common.stream.FixedStreamMessage.onComplete(FixedStreamMessage.java:255)
		at com.linecorp.armeria.internal.common.stream.OneElementFixedStreamMessage.request0(OneElementFixedStreamMessage.java:88)
		at com.linecorp.armeria.internal.common.stream.OneElementFixedStreamMessage.request(OneElementFixedStreamMessage.java:68)
		at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onSubscribe(DeferredStreamMessage.java:386)
		at com.linecorp.armeria.internal.common.stream.FixedStreamMessage.subscribe0(FixedStreamMessage.java:141)
		at com.linecorp.armeria.internal.common.stream.FixedStreamMessage.subscribe(FixedStreamMessage.java:130)
		at com.linecorp.armeria.common.stream.DeferredStreamMessage.safeOnSubscribeToUpstream(DeferredStreamMessage.java:300)
		at com.linecorp.armeria.common.stream.DeferredStreamMessage.delegate(DeferredStreamMessage.java:151)
		at com.linecorp.armeria.common.DeferredHttpResponse.delegate(DeferredHttpResponse.java:47)
		at com.linecorp.armeria.common.DeferredHttpResponse.lambda$delegateWhenComplete$0(DeferredHttpResponse.java:58)
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
		at com.linecorp.armeria.client.retry.RetryingClient.handleRetryDecision(RetryingClient.java:454)
		at com.linecorp.armeria.client.retry.RetryingClient.lambda$handleResponse$8(RetryingClient.java:403)
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
		at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950)
		at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340)
		at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:144)
		at com.linecorp.armeria.client.retry.RetryingClient.lambda$handleResponse$9(RetryingClient.java:401)
		at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
		at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
		at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
		at com.linecorp.armeria.client.retry.RetryingClient.handleResponse(RetryingClient.java:351)
		at com.linecorp.armeria.client.retry.RetryingClient.lambda$doExecute0$5(RetryingClient.java:330)
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
		at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:152)
		at com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:103)
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
		at com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:67)
		at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:258)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:300)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:292)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:429)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:372)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:328)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:314)
		at com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:436)
		at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:335)
		at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:370)
		at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:318)
		at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:308)
		at com.linecorp.armeria.client.Http2ResponseDecoder.onHeadersRead(Http2ResponseDecoder.java:216)
		at com.linecorp.armeria.client.Http2ResponseDecoder.onHeadersRead(Http2ResponseDecoder.java:225)
		at io.netty.handler.codec.http2.Http2FrameListenerDecorator.onHeadersRead(Http2FrameListenerDecorator.java:48)
		at io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onHeadersRead(Http2EmptyDataFrameListener.java:63)
		at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:409)
		at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:337)
		at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:56)
		at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:476)
		at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:484)
		at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:253)
		at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
		at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
		at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
		at io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
		at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
		at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
21:35:42.596 [armeria-common-worker-nio-2-2] DEBUG com.linecorp.armeria.internal.common.AbstractKeepAliveHandler - [id: 0x789255a8, L:/127.0.0.1:56928 - R:localhost/127.0.0.1:8080] Closing an idle client connection
21:35:42.613 [armeria-common-worker-nio-2-2] DEBUG com.linecorp.armeria.internal.common.Http2GoAwayHandler - [id: 0x789255a8, L:/127.0.0.1:56928 - R:localhost/127.0.0.1:8080] Sent a GOAWAY frame: lastStreamId=0, errorCode=NO_ERROR(0)
```

**Comment by ikhoon** [comment] 2022-08-14 12:45
Duplicate of #4367. It has been fixed in 1.18.0

**Closed by ikhoon** 2022-08-14 12:45 UTC
Labels: duplicate
