### ISSUE TITLE
Add body to LoggingClientBuilder

### ISSUE THREAD

**Issue by adriancole** [line/armeria#1997] opened 2019-08-16 01:43 UTC
While we can turn on client dumps, it is very user unfriendly. I'm almost afraid to recommend it because it is too low-level.

When we transitioned from okhttp to armeria, we had to copy/paste a large amount of code to log request/response bodies.. now I think we will need to do that again in zipkin-gcp because the user is having trouble figuring out what is wrong despite having stats. https://github.com/openzipkin/zipkin-gcp/issues/133

Can we please upstream this feature from Zipkin?
https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin2/server/internal/elasticsearch/RawContentLoggingClient.java

**Comment by trustin** [comment] 2019-11-25 11:31
I wonder if you had a chance to play with request/response content previewer:

```java
WebClient.builder()
         .contentPreview(128) // Previews the first 128 bytes
         ...
         .build();
      
```

**Comment by anuraaga** [comment] 2019-12-07 08:26
I remember now that this didn't work because we use gzip encoding. So possibly can be duplicate of #2189

**Comment by trustin** [comment] 2019-12-08 02:10
Yes. Closing in favor of #2189

**Closed by trustin** 2019-12-08 02:10 UTC
Labels: duplicate, new-feature
