### ISSUE TITLE
NullPointerException in CancellationScheduler

### ISSUE THREAD

**Issue by notxcain** [line/armeria#3821] opened 2021-09-09 08:47 UTC
Hey! Sometimes we're getting this `WARN` level log entries while serving gRPC.

Armeria version: 1.7.2 
```
[armeria-common-worker-nio-2-3] WARN com.linecorp.armeria.common.stream.AbstractStreamMessage - Subscriber.onComplete() should not raise an exception. subscriber: com.linecorp.armeria.server.HttpResponseSubscriber@3c6f3220
java.lang.NullPointerException: null
	at com.linecorp.armeria.internal.common.CancellationScheduler.clearTimeout0(CancellationScheduler.java:170)
	at com.linecorp.armeria.internal.common.CancellationScheduler.clearTimeout(CancellationScheduler.java:149)
	at com.linecorp.armeria.server.HttpResponseSubscriber.setDone(HttpResponseSubscriber.java:277)
	at com.linecorp.armeria.server.HttpResponseSubscriber.onComplete(HttpResponseSubscriber.java:328)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:265)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:284)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:276)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:448)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:391)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:338)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:324)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:455)
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.doClose(ArmeriaServerCall.java:389)
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.close(ArmeriaServerCall.java:340)
	at com.linecorp.armeria.server.grpc.FramedGrpcService.lambda$doPost$1(FramedGrpcService.java:213)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124)
	at com.linecorp.armeria.internal.common.CancellationScheduler$CancellationFuture.doComplete(CancellationScheduler.java:505)
	at com.linecorp.armeria.internal.common.CancellationScheduler.invokeTask(CancellationScheduler.java:464)
	at com.linecorp.armeria.internal.common.CancellationScheduler.lambda$init0$2(CancellationScheduler.java:124)
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:522)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by ikhoon** [comment] 2021-09-09 09:25
Hi @notxcain. The bug has been fixed in [1.8.0](https://armeria.dev/release-notes/1.8.0#%EF%B8%8F-bug-fixes). 
See #3564
Please reopen this issue if the problem is not fixed in 1.8.0 or later. 😉

**Closed by ikhoon** 2021-09-09 09:25 UTC

**Comment by ikhoon** [comment] 2021-09-09 09:31
By the way, I used to use your event sourcing library https://github.com/notxcain/aecor. I am glad that you are using Armeria. 🤩

**Comment by notxcain** [comment] 2021-09-09 09:42
@ikhoon awesome, thank you :)

Glad to hear about Aecor, we use Armeria at @whisklabs to run our gRPC services.
