### ISSUE TITLE
how to set json PropertyNamingStrategy SNAKE_CASE？

### ISSUE THREAD

**Issue by RyouZhang** [line/armeria#1751] opened 2019-05-05 11:38 UTC
Armeria has method to set json PropertyNamingStrategy SNAKE_CASE？

**Comment by trustin** [comment] 2019-05-07 07:51
Hi, @RyouZhang. Thanks for a question. I guess your question is about how to change the `PropertyNamingStrategy` of a Jackson `ObjectMapper` when using Armeria's annotated services, right?

As you might already know, by default, Armeria uses the `ObjectMapper` with default settings, which means the JSON documents will be serialized and deserialized without any special transformation.

To use a custom `ObjectMapper` with Armeria, you need to first define a new `RequestConverterFunction` (or `ResponseConverterFunction`) that extends `JacksonRequestConverterFunction` (or `JacksonResponseConverterFunction`):

```java
public static class JacksonSnakeCaseRequestConverter extends JacksonRequestConverter {
    private static final ObjectMapper objectMapper = new ObjectMapper();
    static {
        objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
    }

    public JacksonSnakeCaseRequestConverter() {
        super(objectMapper);
    }
}

public static class JacksonSnakeCaseResponseConverter extends JacksonResponseConverter {
    private static final ObjectMapper objectMapper = new ObjectMapper();
    static {
        objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
    }

    public JacksonSnakeCaseResponseConverter() {
        super(objectMapper);
    }
}
```

Then, you can use `@RequestConverter` (or `@ResponseConverter`) annotation to tell Armeria to use your Jackson converter implementation:

```java
// Annotated service 1
@RequestConverter(JacksonSnakeCaseRequestConverter.class)
@ResponseConverter(JacksonSnakeCaseResponseConverter.class)
public class MyAnnotatedServiceOne { ... }

// Annotated service 2
@RequestConverter(JacksonSnakeCaseRequestConverter.class)
@ResponseConverter(JacksonSnakeCaseResponseConverter.class)
public class MyAnnotatedServiceTwo { ... }
```

Because specifying two annotations for all service classes is tedious, you might want to define a meta-annotation and annotate the service classes with it:

```java
// Meta annotation
@Retention(RetentionPolicy.RUNTIME)
@RequestConverter(JacksonSnakeCaseRequestConverter.class)
@ResponseConverter(JacksonSnakeCaseResponseConverter.class)
public @interface SnakeCaseJsonConversion {}

// Annotated service 1
@SnakeCaseJsonConversion
public class MyAnnotatedServiceOne { ... }

// Annotated service 2
@SnakeCaseJsonConversion
public class MyAnnotatedServiceTwo { ... }
```

Related resources:

- How to write a request or response converter - https://line.github.io/armeria/server-annotated-service.html#conversion-between-an-http-message-and-a-java-object
- How to define a meta annotation - https://line.github.io/armeria/server-annotated-service.html#using-a-composite-annotation

**Comment by anuraaga** [comment] 2019-05-07 07:57
I think this might also be the same as #1696 (see a related discussion at https://github.com/curioswitch/curiostack/issues/301)

**Comment by trustin** [comment] 2019-05-07 08:07
Doh! So, @RyouZhang 's question was rather about gRPC JSON. Sorry about a long yet incorrect answer. :sweat_smile:

**Comment by trustin** [comment] 2019-05-07 08:17
@RyouZhang Would it be fine to mark this issue as a duplicate of #1696?

**Comment by RyouZhang** [comment] 2019-05-08 08:36
yes，I reflect to set the PropertyNamingStrategy, but not userful. close this issuse, I will try go gen code lowcaml json

**Comment by anuraaga** [comment] 2019-05-08 08:38
@RyouZhang Thanks - just for reference, in case it helps, I wonder if you are using Go's standard JSON marshaller for protobuf structs. I think you may find it simpler to use protobuf's native JSON marshaller, which follows the semantics and has relevant options that can be set at runtime

https://godoc.org/github.com/golang/protobuf/jsonpb#Marshaler

**Comment by trustin** [comment] 2019-05-09 00:15
Closing as a duplicate of #1696.

**Closed by trustin** 2019-05-09 00:15 UTC
Labels: duplicate
